version: "3"
services: 
  redis: 
    image: 'redis/redis-stack-server:6.2.6-v12' 
    ports: 
      - '127.0.0.1:6379:6379/tcp' 
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
      - REDIS_ARGS=--save 10 1 --appendonly yes 
    volumes:
        - ./redis-data:/data    

#  redisinsight: 
#    image: 'redislabs/redisinsight:1.14.0' 
#    ports: 
#      - '127.0.0.1:8001:8001' 

#
# Deploying a Redis Stack Cluster using Docker images along with RedisInsight
# https://medium.com/@joshisoftynakul/deploying-a-redis-stack-cluster-using-docker-images-along-with-redisinsight-e3588f038a40
#
# Docker Stack/Compose Redis Instance Not Persisting Data
# https://stackoverflow.com/questions/52824727/docker-stack-compose-redis-instance-not-persisting-data
#
# EOF (2024/03/16)
#
